### premium customer and category A order
POST http://localhost:8080/orders
Content-Type: application/json

{
  "product": {
    "name": "item 1",
    "price": "20",
    "category": "A"
  },
  "quantity": 2,
  "customer": {
    "name": "John Doe",
    "customerSegment": "PREMIUM"
  }
}


### send X times random order
GET http://localhost:8080/orders/5
Content-Type: application/json