version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "docker-management"
    restart: always
    hostname: docker-rabbitmq
    volumes:
      - "rabbitmq:/var/lib/rabbitmq/mnesia"
    ports:
      - "5672:5672"     # port przez ktory mozemy konfigurowac rabbitmq
      - "15672:15672"   # port poprzez ktory mamy udostepniony web manager

  producer:
    image: rabbit-producer-1
    container_name: "producer"
    build:
      context: ./Producer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"

  consumer:
    image: rabbit-consumer-1
    container_name: "consumer-1"
    build:
      context: ./Consumer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"

#  consumer2:
#    image: rabbit-consumer-1
#    container_name: "consumer-2"
#    # no need for build section - we use the same image as for first consumer
#    restart: always
#    depends_on:
#      - rabbitmq
#    ports:
#      - "8082:8081"
#
#  consumer3:
#    image: rabbit-consumer-1
#    container_name: "consumer-3"
#    # no need for build section - we use the same image as for first consumer
#    restart: always
#    depends_on:
#      - rabbitmq
#    ports:
#      - "8083:8081"

volumes:
  rabbitmq:
