spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# queue names for consumers
rabbitmq:
  product-added: "q.products"
  order-placed:
    sales: "q.sales"
    warehouse: "q.warehouse"
    logs: "q.logs"

server:
  port: 8081
