spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  product-added:
    exchange-name: "x.products"
    queue-name: "q.products"
  order-placed:
    exchange-name: "x.orders"
    queue-names:
      - "q.sales"
      - "q.warehouse"
      - "q.logs"
