spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

rabbitmq:
  product-added:
    exchange-name: "x.products"
    queue-name: "q.products"
  order-placed:
    exchange-name: "x.orders"
    queue-names:
      - "q.sales"
      - "q.warehouse"
      - "q.logs"
  categorized-order:
    exchange-name: "x.categorized-orders"
    queue-names:
      - "q.categoryA"
      - "q.premiumCustomers"
      - "q.cheapProductsCategoryC"
    routing-keys:
      - "A.#"
      - "*.premium.*"
      - "C.*.low"
  product-with-dead-letter:
    product-exchange-name: "x.dl-products"
    product-queue-name: "q.dl-products"
    dead-letter-exchange-name: "x.dl-products.dlx"
    dead-letter-queue-name: "q.dl-products.dlq"
    message-TTL: 2000
